-- MySQL Script generated by MySQL Workbench
-- Sun Jul  8 21:06:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 2554622_escola
-- -----------------------------------------------------
USE `2554622_escola` ;

-- -----------------------------------------------------
-- Table `tbprofessor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbprofessor` ;

CREATE TABLE IF NOT EXISTS `tbprofessor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `dtCriacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idProfessor`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tbcurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbcurso` ;

CREATE TABLE IF NOT EXISTS `tbcurso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `idProfessor` INT NOT NULL,
  `dtCriacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCurso`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `tbcurso_tbprofessor_pk` (`idProfessor` ASC),
  CONSTRAINT `tbcurso_tbprofessor_fk`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `tbprofessor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `tbaluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbaluno` ;

CREATE TABLE IF NOT EXISTS `tbaluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `cep` VARCHAR(15) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` INT(10) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `idCurso` INT NOT NULL,
  `dtCriacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idAluno`),
  INDEX `tbaluno_tbcurso_pk` (`idCurso` ASC),
  CONSTRAINT `tbaluno_tbcurso_fk`
    FOREIGN KEY (`idCurso`)
    REFERENCES `tbcurso` (`idCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
