-- MySQL Script generated by MySQL Workbench
-- Sat Jul  7 20:44:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_escola` ;

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_escola` DEFAULT CHARACTER SET utf8 ;
USE `db_escola` ;

-- -----------------------------------------------------
-- Table `db_escola`.`tbprofessor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tbprofessor` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tbprofessor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `dtCriacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idProfessor`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_escola`.`tbcurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tbcurso` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tbcurso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `idProfessor` INT NOT NULL,
  `dtCriacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCurso`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `tbcurso_tbprofessor_pk` (`idProfessor` ASC),
  CONSTRAINT `tbcurso_tbprofessor_fk`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `db_escola`.`tbprofessor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_escola`.`tbaluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tbaluno` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tbaluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `cep` VARCHAR(15) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` INT(10) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `idCurso` INT NOT NULL,
  `dtCriacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idAluno`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `tbaluno_tbcurso_pk` (`idCurso` ASC),
  CONSTRAINT `tbaluno_tbcurso_fk`
    FOREIGN KEY (`idCurso`)
    REFERENCES `db_escola`.`tbcurso` (`idCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `db_escola` ;

-- -----------------------------------------------------
-- Placeholder table for view `db_escola`.`vw_alunoscursoprofessor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_escola`.`vw_alunoscursoprofessor` (`idAluno` INT, `'aluno'` INT, `'curso'` INT, `'professor'` INT);

-- -----------------------------------------------------
-- View `db_escola`.`vw_alunoscursoprofessor`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `db_escola`.`vw_alunoscursoprofessor` ;
DROP TABLE IF EXISTS `db_escola`.`vw_alunoscursoprofessor`;
USE `db_escola`;
CREATE  OR REPLACE VIEW `vw_alunoscursoprofessor` AS
	select	a.idAluno,
			a.nome as 'aluno',
			b.nome as 'curso',
            c.nome as 'professor'
	from tbaluno a
    inner join tbcurso b
    using (idCurso)
    inner join tbprofessor c
    using (idProfessor)
    order by idAluno asc;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
